### ISSUE TITLE
start.sh not found after build

### ISSUE THREAD

**Issue by cre8** [ngineered/nginx-php-fpm#148]
I built the image myself without any error. My steps
```
git clone https://github.com/ngineered/nginx-php-fpm
cd nginx-php-fpm
docker build -t test .
docker run -p 80:80 test
```
 But when I want to start it it throws this error:
`/usr/local/bin/docker-php-entrypoint: exec: line 9: /start.sh: not found`

**Comment by richarvey** [comment]
I can't replicate this error so closing. Please make sure you have the latest repo pulled.

**Comment by Xammie** [comment]
I'm having the same issue. Cloned latest build from github.

```
docker build -t test:latest .
docker run -v /var/www/html test:latest
```

And i get the exact same error:
```
/usr/local/bin/docker-php-entrypoint: exec: line 9: /start.sh: not found
```
I'm on windows 10 using docker installed with the docker toolbox.

**Comment by Xammie** [comment]
The containers running the image richarvey/nginx-php-fpm (that i didn't build) don't have the evironment variable `"LD_PRELOAD"` but the images i build automatically have the environment variable `LD_PRELOAD` set to `/usr/lib/preloadable_libiconv.so php` I can't seem to remove the variable it keeps coming back

**Comment by kevinlisota** [comment]
I have been receiving this same error, on docker version 18.03.0-ce on both Ubuntu and Windows variants, built from source. This same issue is being reported in this[ open issue](https://github.com/richarvey/nginx-php-fpm/issues/210) and maybe [this one](https://github.com/richarvey/nginx-php-fpm/issues/205) as well.

I entered the docker image and start.sh does exist and has correct permissions. Running `exec /usr/bin/supervisord -n -c /etc/supervisord.conf` from bash once inside the running container brings up supervisor and its services as expected.

I've also attempted a modified version of your Dockerfile where I don't run the `start.sh` and simply execute this:
```
CMD ["/usr/bin/supervisord", "-n", "-c /etc/supervisord.conf"]
```
That gives an error of "could not find config file  /etc/supervisord.conf" yet inspection of the container shows that config file is present with correct permissions.

The `docker-php-entrypoint` part of the above error comes from the ENTRYPOINT defined in the PHP base image. Perhaps this needs to be overridden with a later ENTRYPOINT definition for this combined image. I used `ENTRYPOINT []` to remove the default entrypoint from the PHP image.

The issue of not finding the files happens when I use the exec format of CMD. When I change that to the shell format of CMD, then things works as expected. I'm scratching my head here and can't figure out why, but it has something to do with the exec format of CMD.
