### ISSUE TITLE
php.ini not taken into account

### ISSUE THREAD

**Issue by kalumkalac** [ngineered/nginx-php-fpm#43]
Just check out you new build. Although you edit the file */etc/php5/php.ini* in the Dockerfile, the phpinfo() just don't seem to use it. All values are the default ones.
```
Configuration File (php.ini) Path	/etc/php5
Loaded Configuration File	(none)
```

**Comment by richarvey** [comment]
Thanks @kalumkalac I'll check that out asap.

**Comment by richarvey** [comment]
I've linked the php.ini file to /etc/php5/conf.d and this now loads the default like max file upload etc.

**Comment by auchri** [comment]
@richarvey 

That's still the case:

![image](https://cloud.githubusercontent.com/assets/5092164/16233224/ec0e2e3a-37cd-11e6-9c2c-270d4fb39635.png)

But as you can see, it's not necessary to `ln -s /etc/php5/php.ini /etc/php5/conf.d/php.ini`, since php already searches in the `/etc/php5/conf.d` folder for additional .ini files.

I think with the symlink you created you  created to "fix" this issue it's no longer possible to provide a custom php.ini if I'm not wrong?
