### ISSUE TITLE
Undefined GLOB_BRACE

### ISSUE THREAD

**Issue by Sendoushi** [ngineered/nginx-php-fpm#57]
One of our internal libraries uses `GLOB_BRACE` and using this container I'm getting:
```
 Use of undefined constant GLOB_BRACE
```

Ideas on how to solve?

**Comment by richarvey** [comment]
This rings a bell! I'll have a deeper look in my notes for this and let you know asap

**Comment by Sendoushi** [comment]
Awesome! Thanks! Looking forward...

**Comment by richarvey** [comment]
it looks like alpine linux (our base image) doesn't support GLOB_BRACE since it is using musl libc instead of GNU libc.

This is an issue open with PHP as they need to support other systems.

Now not wanting to leave you with a "it wont work, until the upstream patches" message I've had a look and some people are doing the following as a work round:

 call glob() multiple times and then do an array_merge()

I'm not saying this is pretty but it seems to be the best solution until PHP support musl libc. I hope that helps and if you find other work rounds please feel free to add them to this issue.

Ric

**Comment by Sendoushi** [comment]
Sure. That makes some sense. I actually don't understand the need for this in the internal lib but oh well.

Thanks! You're awesome for trying to solve :P By the way... thanks also for a working nginx docker ehehe
